sudo: required

language: python
python:
  - "2.7"

before_install:
  - pip install gunicorn
  - pip install pytest pytest-cov
  - pip install coveralls

install:
  - pip install -r requirements.txt

script:
  - gunicorn -w 4 -b 127.0.0.1:5000 ndrest:app &
  - py.test --cov=./

after_success:
  - coveralls